Part 3: Array Creation Functions
1. Use NumPy built-in functions to generate:
a) A zero matrix of size 4×4
b) A one matrix of size 3×2
c) An identity matrix of size 5×5
d) A constant values array filled with the value 7
e) A random integer array of size (3×4), with values between 10 and 99
2. Use np.arange() to generate an array from 5 to 50 with a step size of 5. Then reshape it into (3×3)

In [1]:
import numpy as np

In [8]:
a=np.zeros((4,4))

In [9]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
b=np.ones((3,2))

In [17]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.full((3,3),fill_value=7) # constant array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [42]:
np.random.randint(10,99,size=(3,4))

array([[52, 39, 69, 13],
       [23, 59, 28, 32],
       [80, 67, 84, 48]], dtype=int32)

In [43]:
n=np.arange(5,50,5)

In [44]:
n

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [52]:
m=n.reshape(-1,1) # it make view of array change in view is equal to chan

In [53]:
m


array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])

In [54]:
m[3,0]=100

In [55]:
m

array([[  5],
       [ 10],
       [ 15],
       [100],
       [ 25],
       [ 30],
       [ 35],
       [ 40],
       [ 45]])

In [56]:
n

array([  5,  10,  15, 100,  25,  30,  35,  40,  45])