Part 4: Indexing and Slicing
Given the array:
arr = np.array([[10, 20, 30, 40],
 [50, 60, 70, 80],
 [90, 100, 110, 120]
])
1. Extract the second row.
2. Extract the first two rows and the second two columns.
3. Extract the last column using slicing.
4. Replace the middle row with [1, 2, 3, 4].

In [1]:
import numpy as py

In [6]:
arr=py.array([[10,20,30,40],
             [50,60,70,80],
            [90,100,110,120]
])

In [8]:
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [11]:
arr[1]

array([50, 60, 70, 80])

In [28]:
arr[1,:2]
arr[0:2]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [43]:
arr[:3,3:]

array([[ 40],
       [ 80],
       [120]])

In [44]:
arr[1]

array([50, 60, 70, 80])